services:
  frontend-app:
    container_name: front-dev
    image: todo-frontend
    build:
      context: ./todo-frontend     
      dockerfile: dev.Dockerfile
    depends_on:      
      - express-app
    environment:
      - VITE_BACKEND_URL=/api
    volumes:
      - ./todo-frontend:/usr/src/app

  express-app:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    depends_on:
     - mongo-db
     - redis-db
    environment:
      - REDIS_URL=redis://redis-db:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo-db:27017/the_database
    volumes:
      - ./todo-backend:/usr/src/app

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    depends_on:      
    - frontend-app
    - express-app
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80



# Added the DBs services since the backend needs it for it to work
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis-db:
    image: redis
    volumes:
      - ./todo-backend/redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:  
  mongo_data:
  